### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by BennettGrider** [BartlomiejF/GaslandsBuilder#1]
Hope you don't mind that I'm not making separate issues for each item!

- White app bar text is very hard to read over the light green background.
- On my device (Galaxy S7) most text is a bit too small, since the font is harder to read than standard fonts.
- Create vehicle screen slots should have left padding (and same with cost on the Add Upgrade/Weapon screens).
- Dropdown button items should have increased padding so users don't tap the wrong item.
- The Add Weapon/Upgrade selection items scrollbar should take up the whole screen.
- Some text (points cost and weapon mount direction) don't use the custom font, and look a bit out of place.
- Adding more than 2 weapons or more than 4 upgrades hides the rest behind a scrollbar that was hard to find.

**Comment by BartlomiejF** [comment]
Thank you for those sugestions. I will try to improve the UI as soon as I get some free time.
