### ISSUE TITLE
Prison perk not only applying to base vehicle cost

### ISSUE THREAD

**Issue by lifesaver666** [BartlomiejF/GaslandsBuilder#11]
If you add the Warden perk "Prison car" to an IceCream Truck the -4 can rebate is applied to the full build, where it's specified in the rule that the rebate is only applied to the base cost of the vehicle, to a minimum of 5 cans. 
Right now, the trucks comes to a cost of 5, but adding a weapon costing 1 can will keep it a 5 where it should cost 6.  Rebate should only save 3 cans, applying only to the vehicle cost, not also the weapons.

Current workaround is adding a smoke dropper and ignoring it.

(Really cool app! Used in recent games, saves place on the table)

**Comment by BartlomiejF** [comment]
Hey! Thanks for those issues. I'll try to make fixes as soon as I get some free time. It is a pleasure to have users who write me about bugs. 
It also seems that I haven't read the rules carefully enough.

**Comment by lifesaver666** [comment]
It's no problem.   The gyrocopter rule isn't even clear in the book.

**Comment by BartlomiejF** [comment]
done
