### ISSUE TITLE
Issue with vehicle selection for a game when over 8 in the list

### ISSUE THREAD

**Issue by lifesaver666** [BartlomiejF/GaslandsBuilder#15]
When having a list of over 8 vehicles, selecting for example the 9th one, will also select the first.
Everything screws up from there (cans total only counts the last vehicle, deselecting the first one deduces it from the total selected cans, even going in minus numbers)

Had to reduce my list down to 8 to be able to use the app again.

**Comment by lifesaver666** [comment]
Since I deleted extra vehicles down to 8, I tried recreating this by adding 1, and testing again, but couldn't reproduce.
Could be an issue with the database update.
(Like the prison vehicles cans cost updated once edited them)

**Comment by BartlomiejF** [comment]
Well that's unexpected, but I have an idea what could be wrong. The fix will take some time. Sorry for inconvenience.

**Comment by lifesaver666** [comment]
Added 2 vehicules, and the issue happened again, selecting the last two also selects the first two.  But, only the selector.   Starting a game shows the correct ones.

**Comment by BartlomiejF** [comment]
It should now work fine. The same occured with on fire token and it was also fixed.
Update your app soon.
