### ISSUE TITLE
Functionality Suggestions

### ISSUE THREAD

**Issue by BennettGrider** [BartlomiejF/GaslandsBuilder#2]
- After saving a car, no way to edit it again or view it with bigger text.
- I think deleting a car should show an alert prompting user confirmation.
- After typing a car name and hitting 'Done', the keyboard is not dismissed.
- Number of build slots defaults to max but should be 0, and seems to have issues when switching cars with weapons/gear already equipped. When messing with this the app crashed too.
- I think it would be helpful to have weapon/upgrade descriptions too, and maybe some sort of car health/hazards tracker?

Hope the feedback helps!

**Comment by BartlomiejF** [comment]
Thanks for the suggestions. I am not sure if I understand the point about the default build slots. The app does not forbid the user to add weapons/upgrades that exceed build slots for homerules/campaign/narrative reasons. I have planned some sort of saved vehicle card generator with trackers. I am also aware that some weapons should not be mounted in any direction(eg. crew fired) but I postponed managing this issue for future releases.
