### ISSUE TITLE
Duplication of hull and perks

### ISSUE THREAD

**Issue by jonascjak** [BartlomiejF/GaslandsBuilder#21]
If you add more than six vehicles and scroll to the bottom and to the top again, the first listed vehicles hull and perks gets duplicated create issues for large can games or teams using warden or beverly as sponsor

**Comment by BartlomiejF** [comment]
Thank you for the issue. I have some clue what is going wrong but the fix, on the first look is pretty laborious so it will take some time.

**Comment by BartlomiejF** [comment]
I believe that the problem is now gone. Please update the app.
